baseURL = 'https://maso.wiki/'
languageCode = 'en-us'
title = 'M.A.S.O - Mixed Arms Space Opera'
theme = "hugo-book"


defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
BookTheme = 'dark'
BookToC = true
BookSearch = true
BookComments = false
BookSection = 'rules'

[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content.en'
  weight = 1

[module.hugoVersion]
extended = true
min = '0.124.0'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup.tableOfContents]
  startLevel = 1

[outputs]
home = [ "HTML", "RSS", "JSON"]
